name: CDK deploy workflow

on:
  push:
    branches:
      - main

jobs: 
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps: 
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install CDK dependencies
        working-directory: code/cdk
        run: npm install

      - name: Build CDK
        working-directory: code/cdk
        run: npm run build

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.OIDC_ROLE}}
          aws-region: us-east-1 

      - name: Deploy CDK Stack
        working-directory: code/cdk
        run: npx cdk deploy --all --require-approval never --verbose

      - name: Install frontend dependencies
        working-directory: code/frontend
        run: npm install

      - name: Build frontend
        working-directory: code/frontend
        run: npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync code/frontend/dist ${{secrets.S3_NAME}} --delete
